name: shopping_list_manager
description: Lista della spesa ordinata per reparti
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  # State Management
  flutter_riverpod: ^2.4.9
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  # Video handling
  video_player: ^2.8.1
  # UI Components
  reorderables: ^0.6.0
  # Utils
  uuid: ^4.1.0
  intl: ^0.20.2
  path_provider: ^2.1.1
  # Icons
  cupertino_icons: ^1.0.8
  emoji_picker_flutter: ^3.1.0
  # Speech Recognition
  speech_to_text: 7.1.0
  permission_handler: ^11.3.1
  fuzzywuzzy: ^1.2.0
  shared_preferences: ^2.5.3
  visibility_detector: ^0.4.0+2
  asset_fill: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/departments/
    - assets/icons/products/
    - assets/images/
    - assets/tutorials/
    - assets/tutorials/completed_lists/
    - assets/tutorials/current_list/
    - assets/tutorials/departments/
    - assets/tutorials/loyalty_cards/
    - assets/tutorials/products/
    - assets/tutorials/recipes/
