name: shopping_list_manager
description: Lista della spesa ordinata per reparti Esselunga
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # UI Components
  reorderables: ^0.6.0
  
  # Utils
  uuid: ^4.1.0
  intl: ^0.20.2
  path_provider: ^2.1.1
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    